### ISSUE TITLE
Testing Output In Prod

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#314] opened 2023-07-02 06:22 UTC
**Describe the bug**
https://github.com/Caltinor/Project-MMO-2.0/blob/a105dfb66035eed32c280e0517be9c98aa9e0f9c/src/main/java/harmonised/pmmo/registry/PerkRegistry.java#L72
https://github.com/Caltinor/Project-MMO-2.0/blob/a105dfb66035eed32c280e0517be9c98aa9e0f9c/src/main/java/harmonised/pmmo/core/perks/PerksImpl.java#L46
https://github.com/Caltinor/Project-MMO-2.0/blob/a105dfb66035eed32c280e0517be9c98aa9e0f9c/src/main/java/harmonised/pmmo/core/perks/PerksImpl.java#L50-L51

Lots of spam in log:
```
output: {}, perkOutput: {}
speedBonuse: 0.0
output: {}, perkOutput: {}
speedBonuse: 0.0
output: {}, perkOutput: {}
speedBonuse: 0.0
output: {}, perkOutput: {}
[16:15:13] [Render thread/INFO] [minecraft/AdvancementList]: Loaded 19 advancements
output: {}, perkOutput: {}
output: {}, perkOutput: {jump_boost_output:0.40999998688697814d}
output: {}, perkOutput: {}
output: {}, perkOutput: {jump_boost_output:0.41099998688697814d}
output: {}, perkOutput: {}
output: {}, perkOutput: {jump_boost_output:0.41099998688697814d}
```

**Expected behavior**
No spam in log

**To Reproduce**
1. Start new game
2. Experience bonus logging

**Screenshots**
![image](https://github.com/Caltinor/Project-MMO-2.0/assets/6394544/75847b67-ca2f-4cca-8a7b-9de7d1a3591a)

**Versions:**
 - Minecraft: 1.20.1
 - Loader: Forge-40.1.35
 - PMMO: 1.20.1-1.0.1

**Comment by sandalle** [comment] 2023-07-04 05:17
Same versions as OP. Even turning off all the MS Loggy options in pmmo-common.toml:
```
        [Common."Ms Loggy"]
                #Which MsLoggy info logging should be enabled?  This will flood your log with data, but provides essential details
                # when trying to find data errors and bug fixing.
                "Info Logging" = []
                #Which MsLoggy debug logging should be enabled?  This will flood your log with data, but provides essential details
                # when trying to find bugs. DEVELOPER SETTING (mostly).
                "Debug Logging" = []
                #Which MsLoggy warn logging should be enabled?  This log type is helpful for catching important but non-fatal issues
                "Warn Logging" = []
                #Which Error Logging should be enabled.  it is highly recommended this stay true.  however, you can
                #disable it to remove pmmo errors from the log.
                "Error Logging" = []
                #Which MsLoggy fatal logging should be enabled?  I can't imagine a situation where you'd want this off, but here you go.
                "Fatal Logging" = []
```

I still get this log spam whenever a player jumps (three jumps generate three logs per player):
```
output: {}, perkOutput: {jump_boost_output:0.41349998688697814d}
output: {}, perkOutput: {jump_boost_output:0.41349998688697814d}
output: {}, perkOutput: {jump_boost_output:0.41349998688697814d}
```

**Comment by SomewhatDamaged** [comment] 2023-07-04 05:22
@sandalle You'll just have to wait for Caltinor to get a look at it. I believe they are on vacation and can't make a fresh build until back at their machine.

**Comment by Caltinor** [comment] 2023-07-04 05:22
OP correctly identified the cause.   This was testing prints that I forgot to remove before publishing. They don't use the MsLoggy system.  It will be fixed in the next update.

**Closed** 2023-07-06 14:04 UTC
Labels: bug, 1-20
