### ISSUE TITLE
Not getting woodcutting an cooking xp

### ISSUE THREAD

**Issue by krjencik** [Caltinor/Project-MMO-2.0#48] opened 2022-07-25 08:16 UTC
**Describe the bug**
Describe exactly what you observed
When breaking trees i dont get woodcutting xp. When cooking food i dont get cooking xp.
**Expected behavior**
get both.
**To Reproduce**
1. Go to '...'enter any world (even a new one counts)
2. Click on '....'make an axe , make a furnace
3. Scroll down to '....' start breaking trees, place down the furnace
4. See error start cooking food.

**Screenshots**

**Versions:**
 - Minecraft: 1.19
 - Loader:  Forge-41.0.110
 - PMMO: 1.19-0.2.4.

**Additional context**

**Comment by krjencik** [comment] 2022-07-25 08:25
p.s.: i didnt tried to smelt ores... + dont know if any other skill is not getting its xp...

**Comment by TheTaterLord** [comment] 2022-07-25 08:27
so is the datapack properly installed and are the things youre trying to cook actually got cooking xp assigned to them( you can check this in the finished items tooltip)

**Comment by Caltinor** [comment] 2022-07-25 13:47
> the datapack is installed by global packs mod, mining for example works, and the wood and food dont have tooltip break xp 

if you press P while hovering over the item or looking at the block, it will show more.
> the datapack is red saying its made for older version of Minecraft... 

that shouldn't matter.  datapacks are forward compatible by design
>I must say sometimes vein mining doesnt work.... but it shows the percentage bonuses (dont know if they work)...

I just updated vein mining with 0.2.4 and it should behave much better now.

**Comment by krjencik** [comment] 2022-07-25 15:13
so.. um.. now the woodcutting seems to work... i had a problem with spruce wood, but in my new world there arent spruces nearby...

**Comment by Caltinor** [comment] 2022-07-25 15:15
yeah, i forgot to add spruce to the official datapack so that wood doesn't work right.

**Comment by krjencik** [comment] 2022-07-26 09:36
... it looks like cooking doesnt work... (cooking chicken: no xp and it says cooking 250, rabbit the same... i think thats enough)
+ smithing works (smelting ores)

**Comment by Caltinor** [comment] 2022-07-26 10:06
> ... it looks like cooking doesnt work... (cooking chicken: no xp and it says cooking 250, rabbit the same... i think thats enough)
> 
> * smithing works (smelting ores)

The datapack, I believe gives 250 cooking XP for crafting, not smelting

**Comment by krjencik** [comment] 2022-07-26 10:42
i didnt get ANY xp ...

**Comment by Caltinor** [comment] 2022-07-26 10:46
Well yeah cuz you can't "craft" chicken. You have to smelt it which there's no setting for.  So that 250 cooking XP is essentially unobtainable unless someone adds a recipe that outputs the cooked food from a crafting grid.   Unless you are saying you added 
```json
"xp_values":{
  "SMELT": {
    "cooking":250
  }
}
```
To your configuration

**Comment by krjencik** [comment] 2022-07-27 07:26
where? i browsed both server config and config and there is nothing in this shape...

**Comment by TheTaterLord** [comment] 2022-07-27 10:40
> where? i browsed both server config and config and there is nothing in this shape...

Because this is all housed in the data pack for 1.19

**Comment by Caltinor** [comment] 2022-07-27 10:43
In any case i'm fixing this with the default data when i push the 0.3.1 fix.  you won't need to do anything on your own unless you want it changed.

**Comment by krjencik** [comment] 2022-07-27 12:47
tyyyyyyyyyyyyyyy

**Closed** 2022-08-01 15:37 UTC
Labels: bug, 1-18-Alpha, 1-19
