### ISSUE TITLE
Perk attribute is not reset back to normal if the level is reduced.

### ISSUE THREAD

**Issue by Silvertide7** [Caltinor/Project-MMO-2.0#368] opened 2023-08-25 05:15 UTC
**Describe the bug**
My character was level 20 dexterity and gained a large increase in movement speed. I then cleared my characters attributes by using the `/pmmo admin @s clear` command. My levels were cleared but my attribute increases were not reset. Setting it to level 0 does decrease the attribute correctly though.

**Expected behavior**
I no longer have the movement speed that 20 dexterity gave me after clearing my levels.

**To Reproduce**
Use the perk
```
		[[Perks.For_Event.SKILL_UP]]
			skill = "dexterity"
			per_level = 0.001
			perk = "pmmo:attribute"
			attribute = "minecraft:generic.movement_speed"
			max_boost = 0.02
```
Go in game and increase your dexterity to 20. Notice the increase in speed. Clear your levels using the above command. You will still have that increase in speed. Logging in and out doesn't fix it.

**Screenshots**

**Versions:**
 - Minecraft: 1.20.1
 - Loader: 47.1.44
 - PMMO: 1.20.1-1.1.3

**Comment by Caltinor** [comment] 2023-08-29 00:30
I am unable to reproduce this issue, however I believe I understand why you experienced the phenomenon that you did.  Because `temp_attribute` was broken in a way that prevented it from ever disabling, I believe the failure of the perk to go back to it's lower state was due to the temp attribute persisting.  Since that persistence was fixed in 2581fe869cb0b5aadaa3563f3711d0700c18a5b3, this issue is resolved

**Closed by Caltinor** 2023-08-29 00:30 UTC
Labels: bug, 1-19, 1-20
