### ISSUE TITLE
Vein Mining Crash

### ISSUE THREAD

**Issue by Tyrius1** [Caltinor/Project-MMO-2.0#36] opened 2022-07-07 14:44 UTC
Was vein mining coal and it crashed right after I mined it

Crash Report:
https://pastebin.com/JvsXKCPC

**Versions:**
 - Minecraft: 1.19
 - PMMO: 1.19-0.1.1

**Comment by Caltinor** [comment] 2022-07-07 15:08
@Tyrius1 Could you see if the issue is resolved with 1.19-0.2.0?  There were some internal changes to how veinmining works that may resolve this issue unintentionally.

**Closed** 2022-07-16 01:37 UTC
Labels: bug
