### ISSUE TITLE
Attributes Keep Their Original Values After Changing Per-Level In Perks

### ISSUE THREAD

**Issue by DootLoot** [Caltinor/Project-MMO-2.0#201] opened 2023-02-04 20:03 UTC
**Describe the Bug**
Changing Per-Level and starting the game again slowly increased the default generic.movement_speed using attribute command

**Expected Behavior**
generic.movement_speed resets on loading, then scales to level based on perk

**To Reproduce**
1. Set agility to level 50
2. close the game
3. increase Per-Level in Agility skill up for the speed attribute
4. open the world
5. Set agility to level 0

**Version**
Minecraft (1.19.2)
Forge (43.2.0)
PMMO (2.1.5)

**Comment by Caltinor** [comment] 2023-02-04 20:07
I am not sure what you are describing.  could you elaborate?   can you also share your pmmo-perks.toml

**Comment by DootLoot** [comment] 2023-02-04 20:28
when i was changing the values for speed using per_level, changing the value changes how much of a boost the perk gives you, but changing it to a number smaller then the original and then decreasing your level causes the mod to decrease the attribute by the new value, which causes the generic stats to be higher then the defaults. This can also happen the other way around too.
[pmmo-Perks_file.txt](https://github.com/Caltinor/Project-MMO-2.0/files/10609602/pmmo-Perks_file.txt)

**Comment by Caltinor** [comment] 2023-02-04 20:58
what happens when you reach level 1 though?  i'm thinking level zero is just creating a mathematical anomaly that wouldn't appear outside of testing/configuring.

**Comment by DootLoot** [comment] 2023-02-04 21:01
it just leaves the value above the default due to the math anomaly, so the generic is left higher then it should be when it scales up again

**Comment by Caltinor** [comment] 2023-03-19 17:01
I have followed the instructions you gave and tested a few cases of my own.  I am not able to replicate this issue.  These are the steps i tool while testing
1. create new world with fresh configurations
2. set agility level to 50
3. use /attribute command to view modifier
4. close game
5. set per_level in config to 0.000000035 (a smaller number than the default)
6. open game and world and use /attribute command to see value still the same
7. set agility to zero
8. use /attribute command to view modifier and confirm value is removed.
9. set agility to lvl 50 again
10. use /attribute command to see value set to new per_level-scaled value
11. close game entirely
12. set per_level in config to 0.005 (larger than the default)
13. open game and use /attribute command to view modifier is same as before closing
14. set agility to zero
15. use /attribute command to view modifier and confirm it is at zero
16. set agility to 50
17. use /attribute command to see modifier is now scaled off the new per_level

Based on this testing, everything is working as intended.  Is there an aspect i missed?

**Closed** 2023-04-08 10:27 UTC
Labels: bug, 1-19, Cannot Reproduce
